'use client';

import { useAuth } from '@/lib/auth-context';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

export default function LandingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && user) {
      router.push('/dashboard');
    }
  }, [user, loading, router]);

  const features = [
    { icon: '🎯', title: 'Goal-Driven', desc: 'Choose from 12 nutrition goals — from fat loss to gut health to family meals' },
    { icon: '🧠', title: 'AI-Powered', desc: 'Personalized plans generated by an AI nutritionist with 30 years of expertise' },
    { icon: '🍽️', title: '7-Day Meal Plans', desc: 'Complete meal plans with recipes, grocery lists, and macros tailored to YOU' },
    { icon: '🔒', title: 'Enterprise Security', desc: 'Your data is encrypted at rest and in transit. GDPR compliant. Your health data stays private.' },
    { icon: '🔄', title: 'Regenerate Anything', desc: "Don't like Monday's dinner? Regenerate just that meal. Your plan, your rules." },
    { icon: '📊', title: 'Progress Tracking', desc: 'Track your journey with tailored metrics for your specific goal' },
  ];

  const goals = [
    { emoji: '🔥', name: 'Fat Loss' },
    { emoji: '💪', name: 'Muscle Gain' },
    { emoji: '⚡', name: 'Body Recomp' },
    { emoji: '🏃', name: 'Sports Performance' },
    { emoji: '💚', name: 'General Health' },
    { emoji: '🏥', name: 'Medical Support' },
    { emoji: '🤰', name: 'Pregnancy' },
    { emoji: '🌱', name: 'Plant-Based' },
    { emoji: '🧬', name: 'Gut Health' },
    { emoji: '⚡', name: 'Energy & Focus' },
    { emoji: '👨‍👩‍👧‍👦', name: 'Family Meals' },
    { emoji: '💜', name: 'ED Recovery' },
  ];

  return (
    <div className="min-h-screen">
      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 glass-card border-0 border-b" style={{ borderRadius: 0, borderColor: 'rgba(255,255,255,0.05)' }}>
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <span className="text-2xl">🥗</span>
            <span className="text-xl font-bold gradient-text">NutriBot</span>
          </div>
          <div className="flex items-center space-x-4">
            <Link href="/auth/login" className="btn-ghost text-sm">Sign In</Link>
            <Link href="/auth/register" className="btn-primary text-sm !px-5 !py-2">Get Started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-5xl mx-auto text-center">
          <div className="inline-block mb-6 px-4 py-1.5 rounded-full text-sm font-medium" style={{ background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.2)', color: '#34d399' }}>
            ✨ Your Personal AI Nutritionist
          </div>
          <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
            Eat smarter.<br />
            <span className="gradient-text">Feel incredible.</span>
          </h1>
          <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            Get a fully personalized nutrition plan in minutes — tailored to your goals, food preferences, lifestyle, and dietary needs. Powered by AI, grounded in science.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/auth/register" className="btn-primary text-lg !px-8 !py-4">
              Create Your Free Plan →
            </Link>
            <a href="#features" className="btn-secondary text-lg !px-8 !py-4">
              See How It Works
            </a>
          </div>
        </div>
      </section>

      {/* Goals carousel */}
      <section className="pb-20 px-6">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-center text-sm font-semibold uppercase tracking-widest text-slate-500 mb-8">
            12 Nutrition Goals. One App.
          </h2>
          <div className="flex flex-wrap justify-center gap-3">
            {goals.map((g, i) => (
              <div
                key={i}
                className="px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 hover:scale-105"
                style={{
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  animationDelay: `${i * 0.1}s`,
                }}
              >
                <span className="mr-1.5">{g.emoji}</span>{g.name}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-4">
            Everything you need to <span className="gradient-text">eat with confidence</span>
          </h2>
          <p className="text-slate-400 text-center mb-16 max-w-2xl mx-auto">
            Not another generic calculator. NutriBot learns about YOU and creates a plan that fits your life.
          </p>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div
                key={i}
                className="glass-card p-8 hover:border-emerald-500/20 transition-all duration-500"
                style={{ animationDelay: `${i * 0.1}s` }}
              >
                <div className="text-4xl mb-4">{f.icon}</div>
                <h3 className="text-xl font-semibold mb-2">{f.title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">
            How it works
          </h2>
          <div className="space-y-8">
            {[
              { step: '01', title: 'Pick your goal', desc: 'Fat loss? Muscle gain? Gut health? Family nutrition? Choose what matters to you.' },
              { step: '02', title: 'Tell us about you', desc: 'A quick questionnaire about your stats, lifestyle, food preferences, and eating habits.' },
              { step: '03', title: 'Get your plan', desc: 'Our AI generates a complete, personalized nutrition plan with meal plans, macros, grocery lists, and more.' },
              { step: '04', title: 'Track & adapt', desc: "Don't like something? Regenerate it. Track your progress. Adjust as you go." },
            ].map((s, i) => (
              <div key={i} className="flex gap-6 items-start">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl flex items-center justify-center text-sm font-bold" style={{ background: 'linear-gradient(135deg, rgba(16,185,129,0.15), rgba(16,185,129,0.05))', color: '#34d399' }}>
                  {s.step}
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-1">{s.title}</h3>
                  <p className="text-slate-400">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-3xl mx-auto text-center glass-card-strong p-12 animate-pulse-glow">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to transform your nutrition?
          </h2>
          <p className="text-slate-400 mb-8 text-lg">
            Join thousands who&apos;ve already ditched generic diet plans for something that actually works.
          </p>
          <Link href="/auth/register" className="btn-primary text-lg !px-10 !py-4">
            Start Your Journey — Free →
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8 px-6" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center space-x-2">
            <span>🥗</span>
            <span className="font-semibold gradient-text">NutriBot</span>
            <span className="text-slate-500 text-sm">© 2024</span>
          </div>
          <p className="text-slate-500 text-xs text-center md:text-right max-w-md">
            This app provides general nutrition guidance. It is not a substitute for professional medical advice.
            Consult a healthcare provider before making significant dietary changes.
          </p>
        </div>
      </footer>
    </div>
  );
}
